apiVersion: skaffold/v1beta6
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: guestbook-backend
    context: backend
  - image: guestbook-frontend
    context: frontend
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}